"""add company content and assets tables

Revision ID: 6a55fcb2f210
Revises: 8c78e92a95dc
Create Date: 2026-01-29 19:17:19.129682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a55fcb2f210'
down_revision = '8c78e92a95dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
