"""Add itinerary images table

Revision ID: 61a371bba247
Revises: f3762efea755
Create Date: 2026-01-28 15:10:57.933563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61a371bba247'
down_revision = 'f3762efea755'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='Image URL'),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_images_itinerary_id'), 'itinerary_images', ['itinerary_id'], unique=False)
    op.create_index('ix_itinerary_images_sort', 'itinerary_images', ['itinerary_id', 'sort_order'], unique=False)
    op.create_index(op.f('ix_accommodations_level_id'), 'accommodations', ['level_id'], unique=False)
    op.drop_constraint('accommodations_level_id_fkey', 'accommodations', type_='foreignkey')
    op.create_foreign_key(None, 'accommodations', 'accommodation_levels', ['level_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agent_type_created_by', 'agent_types', 'users', ['created_by_admin_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_index(op.f('ix_base_tours_accommodation_level_id'), 'base_tours', ['accommodation_level_id'], unique=False)
    op.drop_constraint('base_tours_accommodation_level_id_fkey', 'base_tours', type_='foreignkey')
    op.create_foreign_key(None, 'base_tours', 'accommodation_levels', ['accommodation_level_id'], ['id'], ondelete='SET NULL')
    op.alter_column('exclusions', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment='Detailed description',
               existing_nullable=True)
    op.alter_column('inclusions', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment='Detailed description',
               existing_nullable=True)
    op.alter_column('itineraries', 'difficulty_level',
               existing_type=sa.VARCHAR(length=50),
               comment='e.g. Easy, Moderate, Challenging',
               existing_nullable=True)
    op.alter_column('itineraries', 'number_of_travelers',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('itineraries', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('itineraries', 'deposit_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('itineraries', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=None,
               nullable=False)
    op.alter_column('itineraries', 'payment_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.create_index(op.f('ix_itineraries_accommodation_level_id'), 'itineraries', ['accommodation_level_id'], unique=False)
    op.alter_column('itinerary_days', 'meals_included',
               existing_type=sa.VARCHAR(length=255),
               comment="Meals included e.g. 'Breakfast, Dinner'",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itinerary_days', 'meals_included',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Meals included e.g. 'Breakfast, Dinner'",
               existing_nullable=True)
    op.drop_index(op.f('ix_itineraries_accommodation_level_id'), table_name='itineraries')
    op.alter_column('itineraries', 'payment_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'not_paid'::character varying"),
               nullable=True)
    op.alter_column('itineraries', 'currency',
               existing_type=sa.VARCHAR(length=3),
               server_default=sa.text("'USD'::character varying"),
               nullable=True)
    op.alter_column('itineraries', 'deposit_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('itineraries', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('itineraries', 'number_of_travelers',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               nullable=True)
    op.alter_column('itineraries', 'difficulty_level',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='e.g. Easy, Moderate, Challenging',
               existing_nullable=True)
    op.alter_column('inclusions', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Detailed description',
               existing_nullable=True)
    op.alter_column('exclusions', 'description',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Detailed description',
               existing_nullable=True)
    op.drop_constraint(None, 'base_tours', type_='foreignkey')
    op.create_foreign_key('base_tours_accommodation_level_id_fkey', 'base_tours', 'accommodation_levels', ['accommodation_level_id'], ['id'])
    op.drop_index(op.f('ix_base_tours_accommodation_level_id'), table_name='base_tours')
    op.drop_constraint('fk_agent_type_created_by', 'agent_types', type_='foreignkey')
    op.drop_constraint(None, 'accommodations', type_='foreignkey')
    op.create_foreign_key('accommodations_level_id_fkey', 'accommodations', 'accommodation_levels', ['level_id'], ['id'])
    op.drop_index(op.f('ix_accommodations_level_id'), table_name='accommodations')
    op.drop_index('ix_itinerary_images_sort', table_name='itinerary_images')
    op.drop_index(op.f('ix_itinerary_images_itinerary_id'), table_name='itinerary_images')
    op.drop_table('itinerary_images')
    # ### end Alembic commands ###
