"""Add image_role to BaseTourImage

Revision ID: 8c78e92a95dc
Revises: 1179e943d2b8
Create Date: 2026-01-29 13:00:07.599168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c78e92a95dc'
down_revision = '1179e943d2b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_tour_images', sa.Column('image_role', sa.String(length=50), nullable=True, comment='Role: cover, accommodation_end, inclusions, about_banner, end'))
    op.drop_index('ix_itineraries_unique_code', table_name='itineraries')
    op.create_index(op.f('ix_itineraries_unique_code'), 'itineraries', ['unique_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itineraries_unique_code'), table_name='itineraries')
    op.create_index('ix_itineraries_unique_code', 'itineraries', ['unique_code'], unique=False)
    op.drop_column('base_tour_images', 'image_role')
    # ### end Alembic commands ###
