"""Add image_role

Revision ID: 1179e943d2b8
Revises: 61a371bba247
Create Date: 2026-01-29 12:09:53.363389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1179e943d2b8'
down_revision = '61a371bba247'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_itineraries_unique_code', table_name='itineraries')
    op.create_index('ix_itineraries_unique_code', 'itineraries', ['unique_code'], unique=False)
    op.add_column('itinerary_images', sa.Column('image_role', sa.String(length=50), nullable=True, comment='Role of the image: cover, accommodation_end, inclusions, about_banner, end'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itinerary_images', 'image_role')
    op.drop_index('ix_itineraries_unique_code', table_name='itineraries')
    op.create_index('ix_itineraries_unique_code', 'itineraries', ['unique_code'], unique=True)
    # ### end Alembic commands ###
