"""Initial schema

Revision ID: f3762efea755
Revises: 
Create Date: 2026-01-24 11:07:05.595244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3762efea755'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accommodation_types_name'), 'accommodation_types', ['name'], unique=True)
    op.create_table('accommodation_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accommodation_levels_name'), 'accommodation_levels', ['name'], unique=True)
    op.create_table('agent_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['users.id'], name='fk_agent_type_created_by', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_types_created_by_admin_id'), 'agent_types', ['created_by_admin_id'], unique=False)
    op.create_index(op.f('ix_agent_types_name'), 'agent_types', ['name'], unique=True)
    op.create_table('company_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('LOGO', 'AWARD_BADGE', 'CERTIFICATION', name='asset_type_enum'), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('asset_url', sa.String(length=500), nullable=False, comment='Azure Blob Storage URL'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_assets_asset_type'), 'company_assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_company_assets_is_active'), 'company_assets', ['is_active'], unique=False)
    op.create_index('ix_company_assets_type_active', 'company_assets', ['asset_type', 'is_active'], unique=False)
    op.create_table('exclusions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Name of the exclusion'),
    sa.Column('icon_name', sa.String(length=100), nullable=True, comment="Icon name for UI display (e.g., 'times-circle', 'ban')"),
    sa.Column('category', sa.String(length=100), nullable=True, comment="Category for grouping (e.g., 'Flights', 'Insurance', 'Personal')"),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Order for displaying exclusions'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exclusions_category', 'exclusions', ['category'], unique=False)
    op.create_index(op.f('ix_exclusions_name'), 'exclusions', ['name'], unique=False)
    op.create_index('ix_exclusions_sort', 'exclusions', ['sort_order'], unique=False)
    op.create_table('inclusions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Name of the inclusion'),
    sa.Column('icon_name', sa.String(length=100), nullable=True, comment="Icon name for UI display (e.g., 'plane', 'hotel', 'utensils')"),
    sa.Column('category', sa.String(length=100), nullable=True, comment="Category for grouping (e.g., 'Transport', 'Accommodation', 'Meals')"),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Order for displaying inclusions'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inclusions_category'), 'inclusions', ['category'], unique=False)
    op.create_index(op.f('ix_inclusions_name'), 'inclusions', ['name'], unique=False)
    op.create_index('ix_inclusions_sort', 'inclusions', ['sort_order'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permissions_category', 'permissions', ['category'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('tour_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tour_types_name'), 'tour_types', ['name'], unique=True)
    op.create_table('base_tours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tour_code', sa.String(length=50), nullable=False, comment='Unique tour code e.g., SSC2'),
    sa.Column('tour_name', sa.String(length=255), nullable=False),
    sa.Column('tour_type_id', sa.UUID(), nullable=False),
    sa.Column('number_of_days', sa.Integer(), nullable=False),
    sa.Column('number_of_nights', sa.Integer(), nullable=False),
    sa.Column('hero_image_url', sa.String(length=500), nullable=True, comment='Main image for the tour'),
    sa.Column('default_pricing', sa.Numeric(precision=10, scale=2), nullable=True, comment='Internal default pricing'),
    sa.Column('best_time_to_travel', sa.String(length=255), nullable=True, comment="e.g., 'June to October'"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),

    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accommodation_level_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tour_type_id'], ['tour_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['accommodation_level_id'], ['accommodation_levels.id'], name='base_tours_accommodation_level_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_base_tours_active', 'base_tours', ['is_active'], unique=False)
    op.create_index('ix_base_tours_code', 'base_tours', ['tour_code'], unique=False)
    op.create_index(op.f('ix_base_tours_id'), 'base_tours', ['id'], unique=False)
    op.create_index(op.f('ix_base_tours_is_active'), 'base_tours', ['is_active'], unique=False)
    op.create_index(op.f('ix_base_tours_tour_code'), 'base_tours', ['tour_code'], unique=True)
    op.create_index(op.f('ix_base_tours_tour_name'), 'base_tours', ['tour_name'], unique=False)
    op.create_index(op.f('ix_base_tours_tour_type_id'), 'base_tours', ['tour_type_id'], unique=False)
    op.create_index('ix_base_tours_type', 'base_tours', ['tour_type_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CS_AGENT', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_type_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_type_id'], ['agent_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_agent_type_id'), 'users', ['agent_type_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False, comment="Action performed (e.g., 'create', 'update', 'delete', 'view')"),
    sa.Column('entity_type', sa.String(length=100), nullable=False, comment="Type of entity affected (e.g., 'itinerary', 'user', 'destination')"),
    sa.Column('entity_id', sa.UUID(), nullable=True, comment='ID of the affected entity'),
    sa.Column('description', sa.Text(), nullable=False, comment='Human-readable description of the action'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Additional context data'),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_logs_action', 'activity_logs', ['action'], unique=False)
    op.create_index('ix_activity_logs_created', 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index('ix_activity_logs_entity', 'activity_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index('ix_activity_logs_user', 'activity_logs', ['user_id'], unique=False)
    op.create_index('ix_activity_logs_user_created', 'activity_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('base_tour_exclusions',
    sa.Column('base_tour_id', sa.UUID(), nullable=False),
    sa.Column('exclusion_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['base_tour_id'], ['base_tours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exclusion_id'], ['exclusions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('base_tour_id', 'exclusion_id')
    )
    op.create_table('base_tour_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_tour_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='Azure Blob Storage URL'),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['base_tour_id'], ['base_tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_tour_images_base_tour_id'), 'base_tour_images', ['base_tour_id'], unique=False)
    op.create_index('ix_base_tour_images_sort', 'base_tour_images', ['base_tour_id', 'sort_order'], unique=False)
    op.create_table('base_tour_inclusions',
    sa.Column('base_tour_id', sa.UUID(), nullable=False),
    sa.Column('inclusion_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['base_tour_id'], ['base_tours.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inclusion_id'], ['inclusions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('base_tour_id', 'inclusion_id')
    )
    op.create_table('company_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False, comment="Unique key like 'intro_letter_template', 'about_company', 'cta_message'"),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('placeholders', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='Available placeholders for template'),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_content_key'), 'company_content', ['key'], unique=True)
    op.create_table('destinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('gps_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('gps_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('activities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('best_time_to_visit', sa.String(length=255), nullable=True),
    sa.Column('average_duration', sa.String(length=100), nullable=True, comment="e.g., '2-3 days', '1 week'"),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_country'), 'destinations', ['country'], unique=False)
    op.create_index('ix_destinations_country_region', 'destinations', ['country', 'region'], unique=False)
    op.create_index(op.f('ix_destinations_created_by_user_id'), 'destinations', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_destinations_id'), 'destinations', ['id'], unique=False)
    op.create_index('ix_destinations_location', 'destinations', ['gps_latitude', 'gps_longitude'], unique=False)
    op.create_index(op.f('ix_destinations_name'), 'destinations', ['name'], unique=False)
    op.create_index(op.f('ix_destinations_region'), 'destinations', ['region'], unique=False)
    op.create_table('itineraries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unique_code', sa.String(length=12), nullable=False, comment='Unique code for public URL (e.g., ABC123XYZ456)'),
    sa.Column('tour_title', sa.String(length=255), nullable=False),
    sa.Column('tour_code', sa.String(length=50), nullable=True, comment='Can be same as base tour or custom'),
    sa.Column('tour_type_id', sa.UUID(), nullable=False),
    sa.Column('number_of_days', sa.Integer(), nullable=False),
    sa.Column('number_of_nights', sa.Integer(), nullable=False),
    sa.Column('hero_image_url', sa.String(length=500), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='itinerary_status_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('highlights', sa.Text(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False, comment='Marks if itinerary is fully built and ready'),
    sa.Column('created_from_base_tour_id', sa.UUID(), nullable=True, comment='If created from base tour, track which one'),
    sa.Column('creation_method', sa.Enum('CHOOSE_EXISTING', 'EDIT_EXISTING', 'CUSTOM', name='creation_method_enum'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('accommodation_level_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True, comment='URL of generated PDF document'),
    sa.Column('pdf_generated_at', sa.DateTime(timezone=True), nullable=True, comment='When PDF was last generated'),
    sa.Column('internal_notes', sa.Text(), nullable=True, comment='Internal notes for CS agents, not visible to customers'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),

    sa.Column('can_edit_after_tour', sa.Boolean(), nullable=False, comment='Only admin can edit after tour ends unless this is True'),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True, comment='e.g. Easy, Moderate, Challenging'),
    sa.Column('number_of_travelers', sa.Integer(), nullable=True, default=1),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True, default=0),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True, default=0),
    sa.Column('currency', sa.String(length=3), nullable=True, default='USD'),
    sa.Column('payment_status', sa.String(length=50), nullable=True, default='not_paid'),
    sa.CheckConstraint('number_of_days > 0', name='check_positive_days'),
    sa.CheckConstraint('number_of_nights >= 0', name='check_non_negative_nights'),
    sa.CheckConstraint('return_date >= departure_date', name='check_valid_date_range'),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_from_base_tour_id'], ['base_tours.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tour_type_id'], ['tour_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['accommodation_level_id'], ['accommodation_levels.id'], name='itineraries_accommodation_level_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_itineraries_assigned_to', 'itineraries', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_itineraries_assigned_to_user_id'), 'itineraries', ['assigned_to_user_id'], unique=False)
    op.create_index('ix_itineraries_created_by', 'itineraries', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_itineraries_created_by_user_id'), 'itineraries', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_itineraries_created_from_base_tour_id'), 'itineraries', ['created_from_base_tour_id'], unique=False)
    op.create_index(op.f('ix_itineraries_departure_date'), 'itineraries', ['departure_date'], unique=False)
    op.create_index(op.f('ix_itineraries_id'), 'itineraries', ['id'], unique=False)
    op.create_index(op.f('ix_itineraries_is_deleted'), 'itineraries', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_itineraries_return_date'), 'itineraries', ['return_date'], unique=False)
    op.create_index(op.f('ix_itineraries_status'), 'itineraries', ['status'], unique=False)
    op.create_index(op.f('ix_itineraries_tour_code'), 'itineraries', ['tour_code'], unique=False)
    op.create_index(op.f('ix_itineraries_tour_type_id'), 'itineraries', ['tour_type_id'], unique=False)
    op.create_index(op.f('ix_itineraries_unique_code'), 'itineraries', ['unique_code'], unique=True)
    op.create_table('user_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id')
    )
    op.create_table('accommodations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=True),
    sa.Column('star_rating', sa.Integer(), nullable=True, comment='Star rating (1-5)'),
    sa.Column('location_destination_id', sa.UUID(), nullable=False),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('room_types', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('meal_plans', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('special_features', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('gps_coordinates', sa.String(length=100), nullable=True),
    sa.Column('price_range', sa.String(length=50), nullable=True),
    sa.Column('check_in_time', sa.String(length=20), nullable=True),
    sa.Column('check_out_time', sa.String(length=20), nullable=True),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_destination_id'], ['destinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['type_id'], ['accommodation_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['level_id'], ['accommodation_levels.id'], name='accommodations_level_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accommodations_id'), 'accommodations', ['id'], unique=False)
    op.create_index('ix_accommodations_location', 'accommodations', ['location_destination_id'], unique=False)
    op.create_index(op.f('ix_accommodations_location_destination_id'), 'accommodations', ['location_destination_id'], unique=False)
    op.create_index('ix_accommodations_name', 'accommodations', ['name'], unique=False)
    op.create_index('ix_accommodations_type', 'accommodations', ['type_id'], unique=False)
    op.create_index(op.f('ix_accommodations_type_id'), 'accommodations', ['type_id'], unique=False)
    op.create_table('destination_combinations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination_1_id', sa.UUID(), nullable=False, comment='First destination in the combination'),
    sa.Column('destination_2_id', sa.UUID(), nullable=True, comment='Second destination in the combination (NULL for single destination)'),
    sa.Column('description_content', sa.Text(), nullable=False, comment='Auto-fill description content for this destination combination'),
    sa.Column('activity_content', sa.Text(), nullable=True, comment='Auto-fill activity content for this destination combination'),
    sa.Column('last_edited_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_1_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_2_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_edited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_1_id', 'destination_2_id', name='uq_destination_combination')
    )
    op.create_index('ix_dest_combo_both', 'destination_combinations', ['destination_1_id', 'destination_2_id'], unique=False)
    op.create_index('ix_dest_combo_dest1', 'destination_combinations', ['destination_1_id'], unique=False)
    op.create_index('ix_dest_combo_dest2', 'destination_combinations', ['destination_2_id'], unique=False)
    op.create_index(op.f('ix_destination_combinations_destination_1_id'), 'destination_combinations', ['destination_1_id'], unique=False)
    op.create_index(op.f('ix_destination_combinations_destination_2_id'), 'destination_combinations', ['destination_2_id'], unique=False)
    op.create_index(op.f('ix_destination_combinations_id'), 'destination_combinations', ['id'], unique=False)
    op.create_index(op.f('ix_destination_combinations_last_edited_by_user_id'), 'destination_combinations', ['last_edited_by_user_id'], unique=False)
    op.create_table('destination_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='Azure Blob Storage URL'),
    sa.Column('image_type', sa.Enum('ATMOSPHERIC', 'ACTIVITY', 'GENERAL', name='image_type_enum'), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Order for displaying images'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_destination_images_dest_type', 'destination_images', ['destination_id', 'image_type'], unique=False)
    op.create_index(op.f('ix_destination_images_destination_id'), 'destination_images', ['destination_id'], unique=False)
    op.create_index('ix_destination_images_sort', 'destination_images', ['destination_id', 'sort_order'], unique=False)
    op.create_table('email_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('sent_to_email', sa.String(length=255), nullable=False),
    sa.Column('cc_emails', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('bcc_emails', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('pdf_attached', sa.Boolean(), nullable=False),
    sa.Column('sent_by_user_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivery_status', sa.Enum('SENT', 'DELIVERED', 'FAILED', 'BOUNCED', name='delivery_status_enum'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_logs_itinerary', 'email_logs', ['itinerary_id'], unique=False)
    op.create_index(op.f('ix_email_logs_itinerary_id'), 'email_logs', ['itinerary_id'], unique=False)
    op.create_index('ix_email_logs_sent_at', 'email_logs', ['sent_at'], unique=False)
    op.create_table('itinerary_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('itinerary_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('CREATED', 'EDITED', 'DELETED', 'SENT_EMAIL', 'ASSIGNED', 'UNASSIGNED', 'STATUS_CHANGED', 'PAYMENT_UPDATED', 'COMPLETED', 'CANCELLED', name='action_type_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_activity_logs_action_type'), 'itinerary_activity_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_itinerary_activity_logs_created_at'), 'itinerary_activity_logs', ['created_at'], unique=False)
    op.create_index('ix_itinerary_activity_logs_itinerary', 'itinerary_activity_logs', ['itinerary_id'], unique=False)
    op.create_index(op.f('ix_itinerary_activity_logs_itinerary_id'), 'itinerary_activity_logs', ['itinerary_id'], unique=False)
    op.create_index('ix_itinerary_activity_logs_user_created', 'itinerary_activity_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_itinerary_activity_logs_user_id'), 'itinerary_activity_logs', ['user_id'], unique=False)
    op.create_table('itinerary_exclusions',
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('exclusion_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exclusion_id'], ['exclusions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('itinerary_id', 'exclusion_id')
    )
    op.create_table('itinerary_inclusions',
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('inclusion_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['inclusion_id'], ['inclusions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('itinerary_id', 'inclusion_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.Enum('PAYMENT_CONFIRMED', 'THREE_DAY_ARRIVAL', 'ASSIGNED', 'EDITED', 'CUSTOM', name='notification_type_enum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='priority_enum'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_created', 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_itinerary_id'), 'notifications', ['itinerary_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('payment_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('payment_status', sa.Enum('NOT_PAID', 'PARTIALLY_PAID', 'FULLY_PAID', 'CUSTOM', name='payment_status_enum'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_id', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_records_itinerary', 'payment_records', ['itinerary_id'], unique=False)
    op.create_index(op.f('ix_payment_records_itinerary_id'), 'payment_records', ['itinerary_id'], unique=False)
    op.create_table('travelers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='One traveler should be marked as primary contact'),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Email (required for primary traveler)'),
    sa.Column('phone', sa.String(length=50), nullable=True, comment='Phone (required for primary traveler)'),
    sa.Column('age', sa.Integer(), nullable=True, comment='Age of traveler'),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True, comment='Dietary restrictions, accessibility needs, etc.'),
    sa.Column('profile_notes', sa.Text(), nullable=True, comment='CS agent notes about this traveler (not visible to customer)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_travelers_itinerary', 'travelers', ['itinerary_id'], unique=False)
    op.create_index(op.f('ix_travelers_itinerary_id'), 'travelers', ['itinerary_id'], unique=False)
    op.create_index('ix_travelers_primary', 'travelers', ['is_primary'], unique=False)
    op.create_table('accommodation_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('accommodation_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='Azure Blob Storage URL'),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Order for displaying images'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accommodation_images_accommodation_id'), 'accommodation_images', ['accommodation_id'], unique=False)
    op.create_index('ix_accommodation_images_sort', 'accommodation_images', ['accommodation_id', 'sort_order'], unique=False)
    op.create_table('base_tour_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_tour_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False, comment='Day number in the tour'),
    sa.Column('day_title', sa.String(length=255), nullable=False, comment="Title for the day e.g., 'Arrival in Serengeti'"),
    sa.Column('description', sa.Text(), nullable=False, comment='Detailed description of the day'),
    sa.Column('activities', sa.Text(), nullable=True, comment='Activities for the day'),
    sa.Column('accommodation_id', sa.UUID(), nullable=True),
    sa.Column('atmospheric_image_url', sa.String(length=500), nullable=True, comment='Atmospheric image for the day'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Custom sort order (usually same as day_number)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['base_tour_id'], ['base_tours.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_base_tour_days_accommodation_id'), 'base_tour_days', ['accommodation_id'], unique=False)
    op.create_index(op.f('ix_base_tour_days_base_tour_id'), 'base_tour_days', ['base_tour_id'], unique=False)
    op.create_index('ix_base_tour_days_tour', 'base_tour_days', ['base_tour_id', 'day_number'], unique=False)
    op.create_table('itinerary_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False, comment='Day number in the itinerary'),
    sa.Column('day_title', sa.String(length=255), nullable=False, comment="Title for the day e.g., 'Arrival in Serengeti'"),
    sa.Column('day_date', sa.Date(), nullable=False, comment='Actual date of this day (auto-calculated from departure_date)'),
    sa.Column('description', sa.Text(), nullable=False, comment='Description of the day'),
    sa.Column('activities', sa.Text(), nullable=True, comment='Activities for the day'),
    sa.Column('meals_included', sa.String(length=255), nullable=True, comment="Meals included e.g. 'Breakfast, Dinner'"),
    sa.Column('is_description_custom', sa.Boolean(), nullable=False, comment='True if description was manually entered, False if auto-filled'),
    sa.Column('is_activity_custom', sa.Boolean(), nullable=False, comment='True if activities were manually entered, False if auto-filled'),
    sa.Column('accommodation_id', sa.UUID(), nullable=True),
    sa.Column('atmospheric_image_url', sa.String(length=500), nullable=True, comment='Atmospheric image for the day'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Custom sort order (usually same as day_number)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('day_number > 0', name='check_positive_day_number'),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_days_accommodation_id'), 'itinerary_days', ['accommodation_id'], unique=False)
    op.create_index('ix_itinerary_days_date', 'itinerary_days', ['day_date'], unique=False)
    op.create_index('ix_itinerary_days_itinerary', 'itinerary_days', ['itinerary_id', 'day_number'], unique=False)
    op.create_index(op.f('ix_itinerary_days_itinerary_id'), 'itinerary_days', ['itinerary_id'], unique=False)
    op.create_table('itinerary_featured_accommodations',
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('accommodation_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('itinerary_id', 'accommodation_id')
    )
    op.create_table('base_tour_day_destinations',
    sa.Column('base_tour_day_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['base_tour_day_id'], ['base_tour_days.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('base_tour_day_id', 'destination_id')
    )
    op.create_table('itinerary_day_destinations',
    sa.Column('itinerary_day_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['itinerary_day_id'], ['itinerary_days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('itinerary_day_id', 'destination_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerary_day_destinations')
    op.drop_table('base_tour_day_destinations')
    op.drop_table('itinerary_featured_accommodations')
    op.drop_index(op.f('ix_itinerary_days_itinerary_id'), table_name='itinerary_days')
    op.drop_index('ix_itinerary_days_itinerary', table_name='itinerary_days')
    op.drop_index('ix_itinerary_days_date', table_name='itinerary_days')
    op.drop_index(op.f('ix_itinerary_days_accommodation_id'), table_name='itinerary_days')
    op.drop_table('itinerary_days')
    op.drop_index('ix_base_tour_days_tour', table_name='base_tour_days')
    op.drop_index(op.f('ix_base_tour_days_base_tour_id'), table_name='base_tour_days')
    op.drop_index(op.f('ix_base_tour_days_accommodation_id'), table_name='base_tour_days')
    op.drop_table('base_tour_days')
    op.drop_index('ix_accommodation_images_sort', table_name='accommodation_images')
    op.drop_index(op.f('ix_accommodation_images_accommodation_id'), table_name='accommodation_images')
    op.drop_table('accommodation_images')
    op.drop_index('ix_travelers_primary', table_name='travelers')
    op.drop_index(op.f('ix_travelers_itinerary_id'), table_name='travelers')
    op.drop_index('ix_travelers_itinerary', table_name='travelers')
    op.drop_table('travelers')
    op.drop_index(op.f('ix_payment_records_itinerary_id'), table_name='payment_records')
    op.drop_index('ix_payment_records_itinerary', table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_itinerary_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('ix_notifications_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('itinerary_inclusions')
    op.drop_table('itinerary_exclusions')
    op.drop_index(op.f('ix_itinerary_activity_logs_user_id'), table_name='itinerary_activity_logs')
    op.drop_index('ix_itinerary_activity_logs_user_created', table_name='itinerary_activity_logs')
    op.drop_index(op.f('ix_itinerary_activity_logs_itinerary_id'), table_name='itinerary_activity_logs')
    op.drop_index('ix_itinerary_activity_logs_itinerary', table_name='itinerary_activity_logs')
    op.drop_index(op.f('ix_itinerary_activity_logs_created_at'), table_name='itinerary_activity_logs')
    op.drop_index(op.f('ix_itinerary_activity_logs_action_type'), table_name='itinerary_activity_logs')
    op.drop_table('itinerary_activity_logs')
    op.drop_index('ix_email_logs_sent_at', table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_itinerary_id'), table_name='email_logs')
    op.drop_index('ix_email_logs_itinerary', table_name='email_logs')
    op.drop_table('email_logs')
    op.drop_index('ix_destination_images_sort', table_name='destination_images')
    op.drop_index(op.f('ix_destination_images_destination_id'), table_name='destination_images')
    op.drop_index('ix_destination_images_dest_type', table_name='destination_images')
    op.drop_table('destination_images')
    op.drop_index(op.f('ix_destination_combinations_last_edited_by_user_id'), table_name='destination_combinations')
    op.drop_index(op.f('ix_destination_combinations_id'), table_name='destination_combinations')
    op.drop_index(op.f('ix_destination_combinations_destination_2_id'), table_name='destination_combinations')
    op.drop_index(op.f('ix_destination_combinations_destination_1_id'), table_name='destination_combinations')
    op.drop_index('ix_dest_combo_dest2', table_name='destination_combinations')
    op.drop_index('ix_dest_combo_dest1', table_name='destination_combinations')
    op.drop_index('ix_dest_combo_both', table_name='destination_combinations')
    op.drop_table('destination_combinations')
    op.drop_index(op.f('ix_accommodations_type_id'), table_name='accommodations')
    op.drop_index('ix_accommodations_type', table_name='accommodations')
    op.drop_index('ix_accommodations_name', table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_location_destination_id'), table_name='accommodations')
    op.drop_index('ix_accommodations_location', table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_id'), table_name='accommodations')
    op.drop_table('accommodations')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_itineraries_unique_code'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_tour_type_id'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_tour_code'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_status'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_return_date'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_is_deleted'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_id'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_departure_date'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_created_from_base_tour_id'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_created_by_user_id'), table_name='itineraries')
    op.drop_index('ix_itineraries_created_by', table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_assigned_to_user_id'), table_name='itineraries')
    op.drop_index('ix_itineraries_assigned_to', table_name='itineraries')
    op.drop_table('itineraries')
    op.drop_index(op.f('ix_destinations_region'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_name'), table_name='destinations')
    op.drop_index('ix_destinations_location', table_name='destinations')
    op.drop_index(op.f('ix_destinations_id'), table_name='destinations')
    op.drop_index(op.f('ix_destinations_created_by_user_id'), table_name='destinations')
    op.drop_index('ix_destinations_country_region', table_name='destinations')
    op.drop_index(op.f('ix_destinations_country'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index(op.f('ix_company_content_key'), table_name='company_content')
    op.drop_table('company_content')
    op.drop_table('base_tour_inclusions')
    op.drop_index('ix_base_tour_images_sort', table_name='base_tour_images')
    op.drop_index(op.f('ix_base_tour_images_base_tour_id'), table_name='base_tour_images')
    op.drop_table('base_tour_images')
    op.drop_table('base_tour_exclusions')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index('ix_activity_logs_user_created', table_name='activity_logs')
    op.drop_index('ix_activity_logs_user', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index('ix_activity_logs_entity', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index('ix_activity_logs_created', table_name='activity_logs')
    op.drop_index('ix_activity_logs_action', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_agent_type_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_base_tours_type', table_name='base_tours')
    op.drop_index(op.f('ix_base_tours_tour_type_id'), table_name='base_tours')
    op.drop_index(op.f('ix_base_tours_tour_name'), table_name='base_tours')
    op.drop_index(op.f('ix_base_tours_tour_code'), table_name='base_tours')
    op.drop_index(op.f('ix_base_tours_is_active'), table_name='base_tours')
    op.drop_index(op.f('ix_base_tours_id'), table_name='base_tours')
    op.drop_index('ix_base_tours_code', table_name='base_tours')
    op.drop_index('ix_base_tours_active', table_name='base_tours')
    op.drop_table('base_tours')
    op.drop_index(op.f('ix_tour_types_name'), table_name='tour_types')
    op.drop_table('tour_types')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index('ix_permissions_category', table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('ix_inclusions_sort', table_name='inclusions')
    op.drop_index(op.f('ix_inclusions_name'), table_name='inclusions')
    op.drop_index(op.f('ix_inclusions_category'), table_name='inclusions')
    op.drop_table('inclusions')
    op.drop_index('ix_exclusions_sort', table_name='exclusions')
    op.drop_index(op.f('ix_exclusions_name'), table_name='exclusions')
    op.drop_index('ix_exclusions_category', table_name='exclusions')
    op.drop_table('exclusions')
    op.drop_index('ix_company_assets_type_active', table_name='company_assets')
    op.drop_index(op.f('ix_company_assets_is_active'), table_name='company_assets')
    op.drop_index(op.f('ix_company_assets_asset_type'), table_name='company_assets')
    op.drop_table('company_assets')
    op.drop_index(op.f('ix_agent_types_name'), table_name='agent_types')
    op.drop_index(op.f('ix_agent_types_created_by_admin_id'), table_name='agent_types')
    op.drop_table('agent_types')
    op.drop_index(op.f('ix_accommodation_types_name'), table_name='accommodation_types')
    op.drop_table('accommodation_types')
    # ### end Alembic commands ###
