"""Add meals_included to BaseTourDay

Revision ID: 04363214899f
Revises: 9d88fcb2f321
Create Date: 2026-01-30 13:12:39.465479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04363214899f'
down_revision = '9d88fcb2f321'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_tour_days', sa.Column('meals_included', sa.String(length=100), nullable=True, comment="e.g., 'B, L, D'"))
    op.drop_column('exclusions', 'image_url')
    op.alter_column('inclusions', 'image_url',
               existing_type=sa.VARCHAR(),
               comment='URL to an illustrative image',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inclusions', 'image_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='URL to an illustrative image',
               existing_nullable=True)
    op.add_column('exclusions', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('base_tour_days', 'meals_included')
    # ### end Alembic commands ###
